Book-Project_Goss/Models/Invoice.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Project_Goss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
        }
    
        public int InvoiceID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal ProductTotal { get; set; }
        public decimal SalesTax { get; set; }
        public decimal Shipping { get; set; }
        public decimal InvoiceTotal { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
    }
}

Book-Project_Goss/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Book_Project_Goss.Models;

namespace BookProject.Controllers
{
    public class InvoiceController : Controller
    {
        /// <summary>
        ///     Directs to a page the displays a list of Invoices. Allows the use of searching by all columns,
        ///     or by specific columns and sorts either descending or ascending
        /// </summary>
        /// <param name="id"> search term - string </param>
        /// <param name="filter"> selectd filter - string </param>
        /// <param name="sortBy"> selected column - int </param>
        /// <param name="isDesc"> sort direction - bool</param>
        /// <returns></returns>
        public ActionResult AllInvoices(string id, string filter = "All", int sortBy = 0, bool isDesc = false)
        {
            BooksEntities context = new BooksEntities();
            List<Invoice> invoices = context.Invoices.ToList();

            switch (sortBy)
            {
                case 1:
                    {
                        if (isDesc == true)
                        {
                            invoices = context.Invoices.OrderByDescending(i => i.Customer.Name).ToList();
                        }
                        else
                        {
                            invoices = context.Invoices.OrderBy(i => i.Customer.Name).ToList();
                        }
                        break;
                    }
                case 2:
                    {
                        if (isDesc == true)
                        {
                            invoices = context.Invoices.OrderByDescending(i => i.ProductTotal).ToList();
                        }
                        else
                        {
                            invoices = context.Invoices.OrderBy(i => i.ProductTotal).ToList();
                        }
                        break;
                    }
                case 3:
                    {
                        if (isDesc == true)
                        {
                            invoices = context.Invoices.OrderByDescending(i => i.SalesTax).ToList();
                        }
                        else
                        {
                            invoices = context.Invoices.OrderBy(i => i.SalesTax).ToList();
                        }
                        break;
                    }
                case 4:
                    {
                        if (isDesc == true)
                        {
                            invoices = context.Invoices.OrderByDescending(i => i.InvoiceTotal).ToList();
                        }
                        else
                        {
                            invoices = context.Invoices.OrderBy(i => i.InvoiceTotal).ToList();
                        }
                        break;
                    }
                case 5:
                    {
                        if (isDesc == true)
                        {
                            invoices = context.Invoices.OrderByDescending(i => i.InvoiceDate).ToList();
                        }
                        else
                        {
                            invoices = context.Invoices.OrderBy(i => i.InvoiceDate).ToList();
                        }
                        break;
                    }
                default:
                    {
                        if (isDesc == true)
                        {
                            invoices = context.Invoices.OrderByDescending(i => i.InvoiceID).ToList();
                        }
                        else
                        {
                            invoices = context.Invoices.OrderBy(i => i.InvoiceID).ToList();
                        }
                        break;
                    }
            }

            if (id != null)
            {
                invoices = InvoiceSearch(id, filter, invoices);
            }

            invoices = invoices.Where(i => i.IsDeleted == false).ToList();

            return View(invoices);
        }

        /// <summary>
        ///     grabs a specific invoice by url and id, and redirects to an new page
        ///     where an update can be preformed
        /// </summary>
        /// <param name="id"> invoice id - int </param>
        /// <returns> Update page for invoices </returns>
        [HttpGet]
        public ActionResult InvoiceUpsert(int id)
        {
            BooksEntities context = new BooksEntities();
            InvoiceUpsertModel model = new InvoiceUpsertModel()
            {
                CustomerList = context.Customers.ToList(),
                Invoice = context.Invoices.Where(i => i.InvoiceID == id).FirstOrDefault()
            };

            if (model.Invoice == null)
            {
                model.Invoice = new Invoice();
            }

            return View(model);
        }

        /// <summary>
        ///     Gets the updated info from the update page, adds the new invoice to the list 
        ///     and returns the list page with the updated information
        /// </summary>
        /// <param name="model"> update model </param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult InvoiceUpsert(InvoiceUpsertModel model)
        {
            BooksEntities context = new BooksEntities();
            Invoice invoice = CalculateIvoice(model.Invoice);

            try
            {
                if (context.Invoices.Where(i => i.InvoiceID == invoice.InvoiceID).Count() > 0)
                {
                    //States already exists
                    var check = context.Invoices.Where(i => i.InvoiceID == invoice.InvoiceID).FirstOrDefault();

                    check.CustomerID = invoice.CustomerID;
                    check.InvoiceDate = invoice.InvoiceDate;
                    check.InvoiceTotal = invoice.InvoiceTotal;
                    check.ProductTotal = invoice.ProductTotal;
                    check.SalesTax = invoice.SalesTax;
                    check.Shipping = invoice.Shipping;
                }
                else
                {
                    context.Invoices.Add(invoice);
                }

                context.SaveChanges();
            }
            catch (Exception er)
            {

                throw (er);
            }

            return RedirectToAction("AllInvoices");
        }
        
        /// <summary>
        ///     Calculates the totals for the updated / added invoice
        /// </summary>
        /// <param name="invoice"></param>
        /// <returns></returns>
        private Invoice CalculateIvoice(Invoice invoice)
        {
            BooksEntities context = new BooksEntities();

            List<InvoiceLineItem> items = context.InvoiceLineItems.Where(i => i.InvoiceID == invoice.InvoiceID && i.IsDeleted == false).ToList();

            invoice.ProductTotal = 0;
            foreach (var item in items)
            {
                invoice.ProductTotal = invoice.ProductTotal + (item.ItemTotal * item.Quantity);
            }

            invoice.InvoiceTotal = invoice.ProductTotal + invoice.Shipping + invoice.SalesTax;
            return invoice;
        }

        /// <summary>
        ///     Soft deletes an invoice based on the id that is sent, and redirects back to 
        ///     the list page with updated list of invoices
        /// </summary>
        /// <param name="id"> int </param>
        /// <returns> List View with updated invoices </returns>
        [HttpGet]
        public ActionResult InvoiceDelete(int id)
        {
            BooksEntities context = new BooksEntities();

            try
            {
                Invoice invoice = context.Invoices.Where(i => i.InvoiceID == id).FirstOrDefault();
                invoice.IsDeleted = true;
                context.SaveChanges();
            }
            catch (Exception er)
            {

                throw (er);
            }

            return RedirectToAction("AllInvoices");
        }

        /// <summary>
        ///     Gets the sent id and filter and searches for invoices that match the
        ///     search value and returns an updated list
        /// </summary>
        /// <param name="id"> Value being filtered </param>
        /// <param name="filter"> Section being filtered </param>
        /// <param name="invoices"> List of customers </param>
        /// <returns> an updated list of invoices </returns>
        private List<Invoice> InvoiceSearch(string id, string filter, List<Invoice> invoices)
        {
            id = id.Trim().ToLower();

            if (filter == "All")
            {
                if (int.TryParse(id, out int num))
                {
                    invoices = invoices.Where(i =>
                        i.InvoiceID.ToString().Contains(num.ToString()) ||
                        i.SalesTax.ToString().Contains(num.ToString()) ||
                        i.ProductTotal.ToString().Contains(num.ToString()) ||
                        i.InvoiceTotal.ToString().Contains(num.ToString()) ||
                        i.InvoiceDate.ToString().Contains(num.ToString())).ToList();
                }
                else
                {
                    invoices = invoices.Where(i =>
                        i.InvoiceDate.ToString().ToLower().Contains(id) ||
                        i.Customer.Name.ToLower().Contains(id)).ToList();
                }
            }
            else if (filter == "Id")
            {
                double.TryParse(id, out double num);

                invoices = invoices.Where(c =>
                    c.InvoiceID.ToString().Contains(id.ToString())).ToList();
            }
            else if (filter == "Cust")
            {
                invoices = invoices.Where(c =>
                    c.Customer.Name.ToLower().Contains(id.ToString())).ToList();
            }

Book-Project_Goss/Views/Invoice/AllInvoices.cshtml
@model List<Book_Project_Goss.Models.Invoice>
@{
    ViewBag.Title = "AllInvoices";
}

<div class="Ultility">
    <h2 class="title">Customer Invoices</h2>

    <div class=" container">
        <div class="row thing">
            <div class="col-md-3">
                <input type="text" class="form-control search" id="searchBar" />
            </div>
            <div class="col-md-1">
                <button type="button" class="btn btn-info" onclick="sortable.Search()">Search</button>
            </div>
            <div class="col-md-2">
                <button type="button" class="btn btn-info" onclick="document.querySelector('#searchFilters').classList.toggle('hidden')">Filter Search</button>
            </div>
            <button type="button" class="btn btn-info add" onclick="apiHandler.GET('/Invoice/InvoiceUpsert/0')">Add New</button>
        </div>
    </div>

    <div id="searchFilters" class="hidden">
        <label>All:</label><input type="radio" name="filters" value="All" checked />
        <label>ID:</label><input type="radio" name="filters" value="Id" />
        <label>Customer:</label><input type="radio" name="filters" value="Cust" />
        <label>Product Total:</label><input type="radio" name="filters" value="ProTotal" />
        <label>Invoice Total:</label><input type="radio" name="filters" value="InTotal" />
        <label>Tax:</label><input type="radio" name="filters" value="Tax" />
        <label>Date:</label><input type="radio" name="filters" value="date" />
    </div>
</div>



<table class="table table-hover">
    <thead>
        <tr>
            <th onclick="sortable.sort(0)">ID</th>
            <th onclick="sortable.sort(1)">Customer</th>
            <th onclick="sortable.sort(2)">Product Total</th>
            <th onclick="sortable.sort(3)">Tax</th>
            <th onclick="sortable.sort(4)">Invoice Total</th>
            <th onclick="sortable.sort(5)">Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var invo in Model)
        {
            <tr>
                <td>@invo.InvoiceID</td>
                <td>@invo.Customer.Name</td>
                <td>@invo.ProductTotal.ToString("c")</td>
                <td>@invo.SalesTax.ToString("c")</td>
                <td>@invo.InvoiceTotal.ToString("c")</td>
                <td>@invo.InvoiceDate</td>
                <td><button type="button" class="btn btn-info" onclick="apiHandler.GET('/Invoice/InvoiceUpsert/@invo.InvoiceID')">Edit</button>
                    <button type="button" class="btn btn-danger" onclick="apiHandler.GET('/Invoice/InvoiceDelete/@invo.InvoiceID')">Delete</button></td>
            </tr>
        }
    </tbody>
</table>

<script>
    sortable.URL = '/Invoice/AllInvoices/';
</script>

Book-Project_Goss/Views/Invoice/InvoiceUpsert.cshtml
@model Book_Project_Goss.Models.InvoiceUpsertModel
@{
    ViewBag.Title = "InvoiceUpsert";
}

<div class="jumbotron">
    <h2 class="title">Add / Update an Invoice</h2>

    <p>Make an invoice or update a currently existing one. Items inside invoices currently cannt be added to the invoice directly so to add an item click <a href="/LineItems/LineItemUpsert/?inID=@Model.Invoice.InvoiceID&prodID=">here</a>
        or hit the Add Item button below. The price data also wont update untill the invoice is updated as the items will not be able to be updated till its edited, but we will be sure
        to add that feature in the near future!</p>

    @using (Html.BeginForm("InvoiceUpsert", "Invoice", FormMethod.Post))
    {
        @Html.HiddenFor(i => i.Invoice.InvoiceID)
        <br />
        <div class="cust">
            <label id="inCust">Customer: </label>
            <input list="customers" name="Invoice.CustomerId" class="form-control upsertText" value="@Model.Invoice.CustomerID" />
            <datalist id="customers">
                @foreach (var cust in Model.CustomerList)
                {
                    <option value="@cust.CustomerID">@cust.Name</option>
                }
            </datalist>
        </div>
        <div class="cust">
            <label id="inDate">Invoice Date: </label>
            @Html.TextBoxFor(i => i.Invoice.InvoiceDate, new { @class = "form-control upsertText", type = "date" })
        </div>
        <div class="cust">
            <label id="inProd">Product Total: </label>
            @Html.TextBoxFor(i => i.Invoice.ProductTotal, new { @class = "form-control upsertText", type = "number", step = ".01", readOnly = true })
        </div>
        <div class="cust">
            <label id="inTax">Tax: </label>
            @Html.TextBoxFor(i => i.Invoice.SalesTax, new { @class = "form-control upsertText", type = "number", step = ".01" })
        </div>
        <div class="cust">
            <label id="inShip">Shipping: </label>
            @Html.TextBoxFor(i => i.Invoice.Shipping, new { @class = "form-control upsertText", type = "number", step = ".01" })
        </div>
        <div class="cust">
            <label id="inTotal">Total: </label>
            @Html.TextBoxFor(i => i.Invoice.InvoiceTotal, new { @class = "form-control upsertText", type = "number", step = ".01", readOnly = true })
        </div>


        <button type="submit" class="btn btn-info" onclick="apiHandler.POST('/Invoice/InvoiceUpsert/@Model.Invoice.InvoiceID', @Model.Invoice)">Confirm</button>
        <button type="button" class="btn btn-info" onclick="apiHandler.GET('/LineItems/LineItemUpsert/?inID=@Model.Invoice.InvoiceID&prodID=')">Add Item</button>
}
</div>